name: My First Action
on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello Mishi"
      - name: Say Goodbye
        run: echo "Goodnight Papa!!"
